In [38]:
import numpy as np

# --- Daten ---
rng = np.random.default_rng(0)
X = rng.uniform(-1, 1, (200, 3))           # 200 Punkte, features: a,b,c, Werte zwischen -1 und +1
a, b, c = X.T

d_star = 2*a - b + 0.5*c                   # linear
e_star = b**3 - 2*c + 3*a                  # nichtlinear

d = (d_star > 0).astype(int)               # binär aus linearer Regression
e = (e_star > 0.2).astype(int)             # binär aus nichtlinearer Regression
T = np.stack([d, e], axis=1)               # (N, 2)

# Bias anhängen
Xb = np.hstack([X, np.ones((len(X),1))])   # (N, 4)

# --- Perzeptron (klassische Lernregel) ---
W = rng.normal(scale=0.01, size=(Xb.shape[1], 2))  # (4,2)
lr = 1.0
epochs = 30

for _ in range(epochs):
    for i in rng.permutation(len(Xb)):
        x = Xb[i]                                # (4,)
        t = T[i]                                 # (2,)
        y = (x @ W > 0).astype(int)              # Schritt-Aktivierung
        W += lr * np.outer(x, (t - y))           # Perzeptron-Update

# --- Auswertung ---
Y = (Xb @ W > 0).astype(int)
acc_d = (Y[:,0] == d).mean()
acc_e = (Y[:,1] == e).mean()
print(f"Genauigkeit: d={acc_d:.3f} (linear), e={acc_e:.3f} (nichtlinear)")

# Ein paar Beispiele
print("\n a     b     c    | d*     d | e*     e | d_pred e_pred")
for i in range(8):
    print(f"{a[i]:+5.2f} {b[i]:+5.2f} {c[i]:+5.2f} | "
          f"{d_star[i]:+5.2f}  {d[i]} | {e_star[i]:+5.2f}  {e[i]} |   {Y[i,0]}      {Y[i,1]}")


Genauigkeit: d=1.000 (linear), e=0.975 (nichtlinear)

 a     b     c    | d*     d | e*     e | d_pred e_pred
+0.27 -0.46 -0.92 | +0.55  1 | +2.56  1 |   1      1
-0.97 +0.63 +0.83 | -2.15  0 | -4.31  0 |   0      0
+0.21 +0.46 +0.09 | +0.01  1 | +0.56  1 |   1      1
+0.87 +0.63 -0.99 | +0.61  1 | +4.85  1 |   1      1
+0.71 -0.93 +0.46 | +2.59  1 | +0.41  1 |   1      1
-0.65 +0.73 +0.08 | -1.98  0 | -1.73  0 |   0      0
-0.40 -0.15 -0.94 | -1.12  0 | +0.68  1 |   0      1
-0.75 +0.34 +0.29 | -1.70  0 | -2.80  0 |   0      0


In [39]:
X.shape

(200, 3)

In [40]:
Xb.shape

(200, 4)

In [41]:
X[:3]

array([[ 0.27392337, -0.46042657, -0.91805295],
       [-0.96694473,  0.62654048,  0.82551115],
       [ 0.21327155,  0.45899312,  0.08724998]])

In [42]:
Xb[:3]

array([[ 0.27392337, -0.46042657, -0.91805295,  1.        ],
       [-0.96694473,  0.62654048,  0.82551115,  1.        ],
       [ 0.21327155,  0.45899312,  0.08724998,  1.        ]])

In [43]:
T.shape

(200, 2)

In [44]:
T[:20]

array([[1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1]])

In [45]:
W.shape

(4, 2)

In [46]:
x

array([ 0.34380561,  0.5209732 , -0.78034423,  1.        ])

In [47]:
y

array([0, 1])

In [48]:
t

array([0, 1])

In [49]:
np.outer(x, (t - y))

array([[ 0.,  0.],
       [ 0.,  0.],
       [-0., -0.],
       [ 0.,  0.]])