# Schichten eines YOLO11 Modells anzeigen

In [2]:
import torch
from ultralytics import YOLO

model = YOLO("yolo11n.pt")
for layer_nr, (name, param) in enumerate(model.named_parameters()):    
    print(layer_nr, name, param.shape)

0 model.model.0.conv.weight torch.Size([16, 3, 3, 3])
1 model.model.0.bn.weight torch.Size([16])
2 model.model.0.bn.bias torch.Size([16])
3 model.model.1.conv.weight torch.Size([32, 16, 3, 3])
4 model.model.1.bn.weight torch.Size([32])
5 model.model.1.bn.bias torch.Size([32])
6 model.model.2.cv1.conv.weight torch.Size([32, 32, 1, 1])
7 model.model.2.cv1.bn.weight torch.Size([32])
8 model.model.2.cv1.bn.bias torch.Size([32])
9 model.model.2.cv2.conv.weight torch.Size([64, 48, 1, 1])
10 model.model.2.cv2.bn.weight torch.Size([64])
11 model.model.2.cv2.bn.bias torch.Size([64])
12 model.model.2.m.0.cv1.conv.weight torch.Size([8, 16, 3, 3])
13 model.model.2.m.0.cv1.bn.weight torch.Size([8])
14 model.model.2.m.0.cv1.bn.bias torch.Size([8])
15 model.model.2.m.0.cv2.conv.weight torch.Size([16, 8, 3, 3])
16 model.model.2.m.0.cv2.bn.weight torch.Size([16])
17 model.model.2.m.0.cv2.bn.bias torch.Size([16])
18 model.model.3.conv.weight torch.Size([64, 64, 3, 3])
19 model.model.3.bn.weight torch.Si

# Ein eigenen Objektdetektor aus Python heraus verwenden

In [6]:
from ultralytics import YOLO

# Load a model
#model = YOLO("yolo11n.pt")  # load an official model
model = YOLO("/home/juebrauer/link_to_vcd/10_datasets/58_hardhat_workers/runs/detect/train4/weights/best.pt")  # load a custom model

# Predict with the model
results = model("/home/juebrauer/link_to_vcd/10_datasets/59_hardhat_test_images/001.jpg", verbose=False)  # predict on an image

result = results[0]

xywh = result.boxes.xywh  # center-x, center-y, width, height
xywhn = result.boxes.xywhn  # normalized
xyxy = result.boxes.xyxy  # top-left-x, top-left-y, bottom-right-x, bottom-right-y
xyxyn = result.boxes.xyxyn  # normalized
names = [result.names[cls.item()] for cls in result.boxes.cls.int()]  # class name of each box
confs = result.boxes.conf  # confidence score of each box

In [7]:
xywh

tensor([[553.7574,  77.9223, 116.0840, 155.8445],
        [279.3323, 146.4477, 114.2601, 136.6698],
        [130.0940, 131.5591, 144.5980, 165.1276]], device='cuda:0')

In [8]:
xywhn

tensor([[0.9048, 0.2013, 0.1897, 0.4027],
        [0.4564, 0.3784, 0.1867, 0.3532],
        [0.2126, 0.3399, 0.2363, 0.4267]], device='cuda:0')

In [9]:
xyxy

tensor([[495.7155,   0.0000, 611.7994, 155.8445],
        [222.2022,  78.1128, 336.4624, 214.7826],
        [ 57.7950,  48.9953, 202.3931, 214.1229]], device='cuda:0')

In [10]:
xyxyn

tensor([[0.8100, 0.0000, 0.9997, 0.4027],
        [0.3631, 0.2018, 0.5498, 0.5550],
        [0.0944, 0.1266, 0.3307, 0.5533]], device='cuda:0')

In [11]:
names

['helmet', 'helmet', 'helmet']

In [12]:
confs

tensor([0.8842, 0.8757, 0.8689], device='cuda:0')